# Generated by Django 3.2.7 on 2022-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blogcontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontent',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
