# Generated by Django 3.2.7 on 2022-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220509_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrysettings',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
