# Generated by Django 3.2.7 on 2022-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_industrysettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyuscontent',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
